# This is a config for E2B sandbox template.
# You can use template ID (va2txj0a55o4lb3adf6a) or template name (fluxiai) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("fluxiai") # Sync sandbox
# sandbox = await AsyncSandbox.create("fluxiai") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('fluxiai')

team_id = "f7b269ff-9c03-424a-a3a6-4ed345b9b2e0"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "fluxiai"
template_id = "va2txj0a55o4lb3adf6a"
