# This is a config for E2B sandbox template.
# You can use template ID (4k6nccsrn26zo2a4uuvt) or template name (fluxiai) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("fluxiai") # Sync sandbox
# sandbox = await AsyncSandbox.create("fluxiai") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('fluxiai')

team_id = "5ce53558-bfa5-44da-a8a2-3f54444997c4"
dockerfile = "e2b.Dockerfile"
template_name = "fluxiai"
template_id = "4k6nccsrn26zo2a4uuvt"
start_cmd = "/compile_page.sh"
