"use client"

import React from 'react'
import { Gavel, CheckCircle2, AlertCircle, HelpCircle, FileText, Scale } from 'lucide-react'
import { Badge } from '@/components/ui/badge'

const TermsPage = () => {
  const points = [
    {
      title: "Acceptance of Terms",
      content: "By accessing or using FluxiAi, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing this site."
    },
    {
      title: "License to Use",
      content: "We grant you a personal, non-exclusive, non-transferable, revocable license to use FluxiAi for your own projects. You own the code generated by our AI, but you may not use our platform to build a competing AI engineering service."
    },
    {
      title: "Prohibited Content",
      content: "You may not use FluxiAi to generate code that is malicious, illegal, or violates the rights of others. This includes but is not limited to malware, phishing sites, or copyright-infringing material."
    },
    {
      title: "Subscription and Billing",
      content: "Subscription fees are billed in advance on a monthly or annual basis. You are responsible for all charges incurred under your account. Refunds are handled on a case-by-case basis at our sole discretion."
    },
    {
      title: "Disclaimer of Warranty",
      content: "FluxiAi is provided 'as is' without any warranties, expressed or implied. We do not guarantee that the AI-generated code will be bug-free, secure, or fit for any particular purpose. Always review AI-generated code before deployment."
    },
    {
      title: "Limitation of Liability",
      content: "In no event shall FluxiAi or its developers be liable for any damages (including, without limitation, damages for loss of data or profit) arising out of the use or inability to use the platform."
    }
  ]

  return (
    <div className="w-full min-h-[calc(100vh-5rem)] flex flex-col items-center py-24 px-4">
      <div className="max-w-4xl w-full space-y-16">
        {/* Header */}
        <div className="text-center space-y-6">
          <Badge variant="secondary" className="gap-2 px-4 py-1.5 font-bold rounded-full border-primary/20 bg-background/50 backdrop-blur-md uppercase tracking-widest text-[10px]">
            Legal Center
          </Badge>
          <h1 className="text-5xl md:text-7xl font-black tracking-tighter italic">Terms of <span className="text-primary">Service</span></h1>
          <p className="text-muted-foreground font-medium text-lg">Last updated: April 23, 2026</p>
        </div>

        {/* Content */}
        <div className="space-y-12">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {points.map((point, i) => (
              <div key={i} className="group p-8 rounded-[2.5rem] border border-border/50 bg-card/30 space-y-4 hover:border-primary/40 transition-all duration-500">
                <div className="flex items-center gap-4 mb-2">
                   <div className="p-3 rounded-2xl bg-muted group-hover:bg-primary/10 group-hover:text-primary transition-colors">
                      <CheckCircle2 className="w-5 h-5" />
                   </div>
                   <h3 className="text-xl font-bold">{point.title}</h3>
                </div>
                <p className="text-muted-foreground leading-relaxed text-sm">
                  {point.content}
                </p>
              </div>
            ))}
          </div>

          <div className="p-12 rounded-[3.5rem] bg-gradient-to-br from-background via-card to-background border border-border/40 space-y-8">
            <div className="flex items-center gap-4">
               <div className="p-4 rounded-3xl bg-amber-500/10 text-amber-500">
                  <AlertCircle className="w-8 h-8" />
               </div>
               <div>
                  <h3 className="text-2xl font-black uppercase italic tracking-tighter">Important Notice</h3>
                  <p className="text-sm text-muted-foreground">Please read the following carefully before proceeding.</p>
               </div>
            </div>
            
            <div className="space-y-4 text-sm text-muted-foreground/80 leading-relaxed">
              <p>
                FluxiAi reserves the right to modify or replace these Terms at any time. If a revision is material, we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.
              </p>
              <p>
                By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, please stop using the Service.
              </p>
            </div>

            <div className="pt-4 border-t border-border/40 flex flex-col md:flex-row items-center justify-between gap-6">
              <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-primary">
                 <Scale className="w-4 h-4" /> Governing Law: India
              </div>
              <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-muted-foreground">
                 <HelpCircle className="w-4 h-4" /> ankur.appdev@gmail.com
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default TermsPage
